server:
  port : 8081

spring:
  main:
    banner-mode: "off"
    log-startup-info: "false"

  application:
    name: "Mutant's Analizer"

  data:
    mongodb:
      uri: ${MONGODBURI}
      database: ${MONGODBNAME}

